using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace USB2550HidTest
{
    public enum PrintMode
    {
        RawHex,
        BitIndex
    }
    public enum HID_CMD_GET
    {
        HID_CMD_GET_OCxCON_REGs = 0x01,
        HID_CMD_GET_OCxR_REGs = 0x02,
        HID_CMD_GET_OCxRS_REGs = 0x03,
        HID_CMD_GET_ICxCON_REGs = 0x04,
        HID_CMD_GET_TxCON_REGs = 0x05,
        HID_CMD_GET_PRx_REGs = 0x06,
    }
    public enum HID_CMD_GET_ACK
    {
        HID_CMD_GET_OCxCON_REGs = HID_CMD_GET.HID_CMD_GET_OCxCON_REGs | HID_ACK.HID_ACK_OK_MASK,
        HID_CMD_GET_OCxR_REGs = HID_CMD_GET.HID_CMD_GET_OCxR_REGs | HID_ACK.HID_ACK_OK_MASK,
        HID_CMD_GET_OCxRS_REGs = HID_CMD_GET.HID_CMD_GET_OCxRS_REGs | HID_ACK.HID_ACK_OK_MASK,
        HID_CMD_GET_ICxCON_REGs = HID_CMD_GET.HID_CMD_GET_ICxCON_REGs | HID_ACK.HID_ACK_OK_MASK,
        HID_CMD_GET_TxCON_REGs = HID_CMD_GET.HID_CMD_GET_TxCON_REGs | HID_ACK.HID_ACK_OK_MASK,
        HID_CMD_GET_PRx_REGs = HID_CMD_GET.HID_CMD_GET_PRx_REGs | HID_ACK.HID_ACK_OK_MASK
    }
    public enum HID_CMD_SET
    {
        HID_CMD_SET_OCxCON_REGs = HID_CMD_GET.HID_CMD_GET_OCxCON_REGs | 0x10,
        HID_CMD_SET_OCxR_REGs = HID_CMD_GET.HID_CMD_GET_OCxR_REGs | 0x10,
        HID_CMD_SET_OCxRS_REGs = HID_CMD_GET.HID_CMD_GET_OCxRS_REGs | 0x10,
        HID_CMD_SET_ICxCON_REGs = HID_CMD_GET.HID_CMD_GET_ICxCON_REGs | 0x10,
        HID_CMD_SET_TxCON_REGs = HID_CMD_GET.HID_CMD_GET_TxCON_REGs | 0x10,
        HID_CMD_SET_PRx_REGs = HID_CMD_GET.HID_CMD_GET_PRx_REGs | 0x10,
        PWM_DUTY = 0x19
    }
    public enum HID_CMD_SET_ACK
    {
        PWM_DUTY = HID_CMD_SET.PWM_DUTY | HID_ACK.HID_ACK_OK_MASK
    }
    public enum HID_CMD
    {
        LOAD_SETTINGS_FROM_EEPROM = 0x07,
        SAVE_SETTINGS_TO_EEPROM = 0x17,
        HID_CMD_IC_GET_LAST_CAPTURED_VALUES = 0x08,
        FAN_RPM_GET_VALUES = 0x0A
    }
    public enum HID_CMD_ACK
    {
        HID_CMD_IC_GET_LAST_CAPTURED_VALUES = HID_CMD.HID_CMD_IC_GET_LAST_CAPTURED_VALUES | HID_ACK.HID_ACK_OK_MASK,
        LOAD_SETTINGS_FROM_EEPROM = HID_CMD.LOAD_SETTINGS_FROM_EEPROM | HID_ACK.HID_ACK_OK_MASK,
        SAVE_SETTINGS_TO_EEPROM = HID_CMD.SAVE_SETTINGS_TO_EEPROM | HID_ACK.HID_ACK_OK_MASK,
        FAN_RPM_GET_VALUES = HID_CMD.FAN_RPM_GET_VALUES | HID_ACK.HID_ACK_OK_MASK,
    }

    public enum HID_ACK
    {
        HID_ACK_OK_MASK = 0x80,
        HID_ACK_ERROR_MASK = 0xFF
    }
}
